# This file is used to configure connection manager clients
# Command line configuration will override the one present in this file

---
Entity_type: Server

# IP address of the server
address: "0.0.0.0"

# Port used for client connection
port: 65432

# Port used for the web server
web_port: 5000

# Timeout in seconds to set for the client.
# Passed that time the client connection will be ended
# If 0 is given, no timeout will be applied
timeout: 0

# Comment that will be sent to the other client when they try to access
# a resource that you are using
comment: I'm just trying the template cfg file

# The time in seconds to wait before re attributing a resource
# This time allow user to reconnect in case of accidental deconnection
resource_free_delay: 10

# The number of time the server will check for client reconnexion
reconnexion_retries: 10

...
