# This file is used to configure connection manager clients
# Command line configuration will override the one present in this file

---
Entity_type: Server

# IP address of the server
address: localhost

# Port used for client connection
port: 65432

# Timeout in seconds to set for the client.
# Passed that time the client connection will be ended
# If 0 is given, no timeout will be applied
timeout: 2

# Comment that will be sent to the other client when they try to access
# a resource that you are using
comment: I'm just trying the template cfg file



...
